### ISSUE TITLE
Add LICENSE, please

### ISSUE THREAD

**Issue by TileHalo** [FabriceCastel/gvcci#1]
Hi!

Thanks for your work! I'm (probably) dropping few PRs myself (formatting main etc). Before I can do that, can you please add LICENSE file, so that the license is clear.

 Also, as a side note I'm happy to contribute some more code.

**Comment by FabriceCastel** [comment]
Hi TileHalo, thanks for the suggestion. I've now added an MIT license to the project.

Your contributions will be welcomed!
